### ISSUE TITLE
Enterprise version on Windows 11/Desktop Docker not working

### ISSUE THREAD

**Issue by hockersmithjr** [OpenC3/cosmos#1491]
**Describe the bug**
Host computer CPU/Disk pegs once a plugin with interfaces gets installed.  Enterprise/Open Source .env and compose.yaml near the same and are the defaults.

**To Reproduce**
Use default settings, add a plugin with an interface.  Notice host computer resources peg out.

**Expected behavior**
Works like the open source version.

**Screenshots**
2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * Configuration loaded
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.779 * monotonic clock: POSIX clock_gettime
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.781 * Running mode=standalone, port=6380.
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.787 * Server initialized
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.788 * Ready to accept connections tcp

2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
2024-08-20 15:45:28 1:C 20 Aug 2024 22:45:28.778 * Configuration loaded
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.778 * monotonic clock: POSIX clock_gettime
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.781 * Running mode=standalone, port=6379.
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.788 * Server initialized
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.789 * Loading RDB produced by version 7.2.5
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.789 * RDB age 602 seconds
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.789 * RDB memory usage when created 2.24 Mb
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.795 * Done loading RDB, keys loaded: 35, keys expired: 0.
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.796 * DB loaded from disk: 0.007 seconds
2024-08-20 15:45:28 1:M 20 Aug 2024 22:45:28.796 * Ready to accept connections tcp

2024-08-20 15:34:32.678 | INFO | DEFAULT__REDUCER__GND | Shutting down microservice comfe_thread'
2024-08-20 15:34:26.311 | FATAL | DEFAULT__REDUCER__GND | Fatal Exception! Exiting...
2024-08-20 15:34:26.242 | ERROR | DEFAULT__REDUCER__GND | CannotConnectError : Unknown Error (hiredis_read) (redis://openc3-redis-ephemeral:6380) (redis://openc3-redis-ephemeral:6380)
/usr/lib/ruby/gems/3.2.0/gems/hiredis-client-0.22.2/lib/redis_client/hiredis_connection.rb:92:in `_read'
/usr/lib/ruby/gems/3.2.0/gems/hiredis-client-0.22.2/lib/redis_client/hiredis_connection.rb:92:in `read'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/connection_mixin.rb:52:in `block in call_pipelined'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/connection_mixin.rb:50:in `times'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/connection_mixin.rb:50:in `call_pipelined'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:771:in `block in connect'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/middlewares.rb:16:in `call'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:770:in `connect'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:732:in `raw_connection'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:697:in `ensure_connected'
/usr/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:431:in `pipelined'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis/client.rb:109:in `pipelined'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis.rb:104:in `block in pipelined'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis.rb:147:in `block in synchronize'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis.rb:147:in `synchronize'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis.rb:147:in `synchronize'
/usr/lib/ruby/gems/3.2.0/gems/redis-5.2.0/lib/redis.rb:103:in `pipelined'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_autoload.rb:44:in `block in pipelined'
/usr/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
/usr/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
/usr/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
/usr/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
/usr/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_autoload.rb:61:in `with'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_autoload.rb:43:in `pipelined'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_queued.rb:72:in `process_queue'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_queued.rb:85:in `store_thread_body'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/utilities/store_queued.rb:59:in `block in initialize'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/top_level.rb:408:in `block in safe_thread'
2024-08-20 15:34:26.235 | ERROR | DEFAULT__REDUCER__GND | OpenC3::EphemeralStoreQueued thread unexpectedly died. Retries: 0 of 0
2024-08-20 15:34:30.216 | INFO | DEFAULT__MULTI__DNL | Shutting down microservice complete: DEFAULT__MULTI__DNL
2024-08-20 15:34:29.457 | FATAL | DEFAULT__MULTI__DNL | Microservice DEFAULT__COMMANDLOG__DNL dying from exception
CannotConnectError : Unknown Error (hiredis_read) (redis://openc3-redis-ephemeral:6380)

**Environment (please complete the following information):**

- OS: Windows 11
- OpenC3 COSMOS Version [5.17.1]
- Browser: [Edge]

**Comment by ryanmelt** [comment]
Please reach out to support@openc3.com.  I don't recognize @hockersmithjr as one of our Enterprise customers.

Interfaces do work fine on Enterprise on Windows.  Your later errors look like the Redis-Ephemeral container is not up, from the perspective of one of our data reduction microservices.   I also don't see anything related to Interfaces in your provided output.
