### ISSUE TITLE
Problem running xtce_converter with 5.1.1

### ISSUE THREAD

**Issue by DavidWathen** [OpenC3/cosmos#294]
I installed a the new 5.1.1 release on a new Ubuntu system and was able to successfully connect to the OpenC3 UI.

I then tried to run the xtce_converter on the demo project but ran into the following issue:

./openc3.sh cli xtce_converter --plugin plugins/DEFAULT/openc3-cosmos-demo/openc3-cosmos-demo-5.1.1.gem --output xtce_output
Installing openc3-cosmos-demo-5.1.1.gem
Error: You don't have write permissions for the /usr/lib/ruby/gems/3.1.0 directory.
/usr/local/lib/site_ruby/3.1.0/rubygems/installer.rb:720:in `verify_gem_home'
/usr/local/lib/site_ruby/3.1.0/rubygems/installer.rb:910:in `pre_install_checks'
/usr/local/lib/site_ruby/3.1.0/rubygems/installer.rb:302:in `install'
/usr/local/lib/site_ruby/3.1.0/rubygems/resolver/specification.rb:104:in `install'
/usr/local/lib/site_ruby/3.1.0/rubygems/request_set.rb:194:in `block in install'
/usr/local/lib/site_ruby/3.1.0/rubygems/request_set.rb:182:in `each'
/usr/local/lib/site_ruby/3.1.0/rubygems/request_set.rb:182:in `install'
/usr/local/lib/site_ruby/3.1.0/rubygems/dependency_installer.rb:252:in `install'
/usr/local/lib/site_ruby/3.1.0/rubygems.rb:551:in `install'
/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/models/gem_model.rb:84:in `install'
/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/models/plugin_model.rb:154:in `install_phase2'
/openc3/bin/openc3cli:253:in `xtce_converter'
/openc3/bin/openc3cli:518:in `<main>'

I installed ruby 3.1.2 using (sudo snap install ruby --classic) but experience the same failure.

Could you please help resolve this issue. 

Thanks,

David

**Comment by DavidWathen** [comment]
Discovered I have to use cliroot. Not sure why. 

./openc3.sh cliroot xtce_converter --plugin plugins/DEFAULT/openc3-cosmos-demo/openc3-cosmos-demo-5.1.1.gem --output xtce_output

**Comment by DavidWathen** [comment]
Thanks for your reply.

I would suggest that your documentation (https://openc3.com/docs/v5/xtce) be updated to reflect the need to use cliroot.

Do you have any pointers to xtce viewer/editor tools?

I tried using the xtcetool (https://gitlab.com/dovereem/xtcetools) and I did get it to view the xtce file generated by the OpenC3 xtce_converter once I made the following changes.

1) Update referenced schemaLocation:
        http://www.omg.org/space/xtce http://www.omg.org/spec/XTCE/20061101/06-11-06.xsd
                                                        replaced with:
        http://www.omg.org/space/xtce SpaceSystemV1.2-27Feb2014-mods.xsd
        
2) Fix spelling:
        twosCompliment
              replaced with:
        twosComplement

3) Remove uneeded <xtce:ArgumentList/> to fix Compliance Error:

ERROR:
XML Schema Compliance Error: ( line 3273 column 29 ) cvc-complex-type.2.4.b: The content of element 'xtce:ArgumentList' is not complete. One of '{"http://www.omg.org/space/xtce":Argument}' is expected.
        
David
