### ISSUE TITLE
target_name reserved 500 error

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#517]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
using VARIABLE target_name in the plugin.txt causes a code 500 error but does not tell user why. 

**To Reproduce**

1. Create plugin.txt with a VARIABLE using target_name
2. Generate .gem
3. Attempt to upload

**Expected behavior**
Error banner telling user that VARIABLE name "target_name" is reserved

**Screenshots**
Error in GUI
![image](https://user-images.githubusercontent.com/101339004/221711316-8ba0a634-c4f9-40d3-a973-fe58026f3f3f.png)

Log from cmd-tlm-api-1 container logs:
2023-02-27 18:16:15 E, [2023-02-27T23:16:15.211390 #14] ERROR -- : [faf0dddd-f0be-4e1f-81ab-9da810251455] RuntimeError : 
2023-02-27 18:16:15 VARIABLE name 'target_name' is reserved
2023-02-27 18:16:15 
2023-02-27 18:16:15 /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.0/lib/openc3/config/config_parser.rb:460:in `parse_errors'
2023-02-27 18:16:15 /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.0/lib/openc3/config/config_parser.rb:216:in `parse_loop'
2023-02-27 18:16:15 /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.0/lib/openc3/config/config_parser.rb:216:in `parse_file'
2023-02-27 18:16:15 /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.0/lib/openc3/models/plugin_model.rb:108:in `install_phase1'
2023-02-27 18:16:15 /src/app/controllers/plugins_controller.rb:45:in `create'

**Environment (please complete the following information):**

- OS: Windows 10
- OpenC3 COSMOS Version 5.5.0
- Browser
  -- [] Internet Explorer (IE)
  -- [x] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by jmthomas** [comment]
Sorry about that @MTI-twalker. We added this check and it's not getting percolated up correctly and displayed.
