### ISSUE TITLE
Easily Load Plugins from Host Command Line

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#520]

**Comment by tj-scherer** [comment]
This seems to exist [here](https://github.com/OpenC3/cosmos/blob/a3222baa88d30844b84f8e05d326979f494cb896/openc3/bin/openc3cli#L319), but I am having issues with it. My plugin uses tcpip_client_interface.rb, with COSMOS v5.2.2.

```log
/usr/lib/ruby/3.1.0/socket.rb:227:in `getaddrinfo': getaddrinfo: Name does not resolve (Redis::CannotConnectError)
        from /usr/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:111:in `connect'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:671:in `new'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:671:in `block in connect'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client/middlewares.rb:12:in `connect'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:670:in `connect'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:657:in `raw_connection'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:624:in `ensure_connected'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-client-0.14.0/lib/redis_client.rb:224:in `call_v'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-5.0.6/lib/redis/client.rb:73:in `call_v'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-5.0.6/lib/redis.rb:167:in `block in send_command'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-5.0.6/lib/redis.rb:166:in `synchronize'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-5.0.6/lib/redis.rb:166:in `send_command'
        from /usr/lib/ruby/gems/3.1.0/gems/redis-5.0.6/lib/redis/commands/hashes.rb:195:in `hkeys'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/utilities/store_autoload.rb:74:in `public_send'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/utilities/store_autoload.rb:74:in `block in method_missing'
        from /usr/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
        from /usr/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
        from /usr/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
        from /usr/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
        from /usr/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/utilities/store_autoload.rb:74:in `method_missing'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/utilities/store_autoload.rb:69:in `public_send'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/utilities/store_autoload.rb:69:in `method_missing'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/models/model.rb:52:in `names'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.2/lib/openc3/models/scope_model.rb:42:in `names'
        from /openc3/bin/openc3cli:324:in `load_plugin'
        from /openc3/bin/openc3cli:507:in `<main>'
```
