### ISSUE TITLE
init container stuck in error loop using Podman on Mac 

### ISSUE THREAD

**Issue by scandey** [OpenC3/cosmos#620]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Continuing my quest to get COSMOS running on Podman on my new Mac, the init container is throwing a `)rrno::EACCESnied @ dir_s_mkdir - /plugins/DEFAULT/targets_modified` error. Podman by default does not give root access to containers, should that be needed here to generate the `targets_modified` folder? The cloned project folder is in my home directory and my user account has permissions for the `/plugins/DEFAULT`. 

Init log
```
Tue Apr 18 06:10:59 UTC 2023
2023-04-18T06:10:59Z waiting for Minio http://openc3-minio:9000 RC: 0
2023-04-18T06:11:00Z waiting for Redis. RC: 0
2023-04-18T06:11:01Z waiting for Redis Ephemeral. RC: 0
Checking for needed migrations...
Migrations complete
Added `openc3minio` successfully.
Added policy `script` successfully.
Added user `scriptrunnerminio` successfully.
Policy `script` is set on user `scriptrunnerminio`
No version change detected for: openc3-tool-base-5.6.0.gem__20230418061019
)rrno::EACCESnied @ dir_s_mkdir - /plugins/DEFAULT/targets_modified
        from /usr/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
        from /usr/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /usr/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
        from /usr/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
        from /usr/lib/ruby/3.1.0/fileutils.rb:211:in `each'
        from /usr/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:506:in `build_local_catalog'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:532:in `sync_with_bucket'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:333:in `block in sync_targets_modified'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:332:in `each'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:332:in `sync_targets_modified'
        from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.6.0/lib/openc3/utilities/local_mode.rb:84:in `local_init'
        from /openc3/bin/openc3cli:716:in `<main>'
Local init running: /plugins exists
Local init found scope: DEFAULT
Tue Apr 18 06:11:05 UTC 2023
Restoring gems to pristine condition...
Restored openc3-tool-base-5.5.2
Restored openc3-tool-base-5.6.0
Tue Apr 18 06:11:05 UTC 2023
2023-04-18T06:11:05Z waiting for Minio http://openc3-minio:9000 RC: 0
```

**To Reproduce**

Clone cosmos-project and launch with Podman on Mac. Check init container logs for error. 

**Expected behavior**
Init launches and exits cleanly. 

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac OS 13.3.1
- OpenC3 COSMOS Version [e.g. 5.0.6]: 5.6.0
- Browser
  -- [] Internet Explorer (IE)
  -- [] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [x] Safari

**Comment by scandey** [comment]
Oops, I missed the last few lines of the COSMOS / Podman tutorial page:

Edit compose.yaml and uncomment the user: 0:0 lines and comment the user: “${OPENC3_USER_ID}:${OPENC3_GROUP_ID}” lines.

Once I'd followed those instructions the permission errors resolved.
