### ISSUE TITLE
Interface can't find protocol when target gets unmapped

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#908]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**

I have a plugin with one target and two interfaces, one serial and the other TCP. Both use the same custom protocol. Upon installation I have the target mapped to the ethernet interface and tlm-only mapped to the serial interface. This works fine.

However, when I use `map_target_to_interface` to switch it completely to one interface or the other I begin seeing errors that my custom protocol file cannot be found for the unmapped interface and the unmapped interface also disappears from the Interfaces tab in the Command and Telemetry Server. I can stop the error messages if I map the target's tlm to the old interface so that it's attached to both of them again.

**To Reproduce**

1. Create a plugin with one target and two interfaces which use a custom protocol in `./TARGET/lib/<protocol>.rb`
3. Map the target to just one interface
4. See errors

**Expected behavior**

I should be able to freely map the target to whichever interface I want to use and get no errors. Also both interfaces should remain in the Interfaces tab of the Command and Telemetry Server.

**Screenshots**

The starting status is UUT2DEV is mapped tlm/cmd to UUT2DEV_ETH and only tlm-mapped to UUT2DEV_SER. Then I run `map_target_to_interface('UUT2DEV', 'UUT2DEV_SER')` in the temp script there.

Command Telemetry Server messages:

```
2023-11-02 15:58:30.374	
INFO	SCRIPT__RUNNER__API	
Script started: __TEMP__/2023_11_02_14_33_05_820_temp.rb
2023-11-02 15:58:32.403	
INFO	CMD__TLM__API	
Target UUT2DEV mapped to Interface UUT2DEV_SER
2023-11-02 15:58:37.045	
INFO	MicroserviceOperator	
Changed microservice detected: DEFAULT__INTERFACE__UUT2DEV_ETH
Was: {"name"=>"DEFAULT__INTERFACE__UUT2DEV_ETH", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_ETH"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>["UUT2DEV"], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698961344919129054, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
Is: {"name"=>"DEFAULT__INTERFACE__UUT2DEV_ETH", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_ETH"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>[], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312399050821, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:37.047	
INFO	MicroserviceOperator	
Changed microservice detected: DEFAULT__INTERFACE__UUT2DEV_SER
Was: {"name"=>"DEFAULT__INTERFACE__UUT2DEV_SER", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_SER"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>["UUT2DEV"], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698961491636271498, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
Is: {"name"=>"DEFAULT__INTERFACE__UUT2DEV_SER", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_SER"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>["UUT2DEV"], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312402951028, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:37.048	
INFO	MicroserviceOperator	
Soft shutting down process: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:37.048	
INFO	MicroserviceOperator	
Soft shutting down process: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:37.049	
ERROR	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: Error reading from interface
2023-11-02 15:58:37.049	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: Closing from signal
2023-11-02 15:58:37.049	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: Connection Lost: Interrupt : 
2023-11-02 15:58:37.054	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: Connection Lost: Interrupt : 
2023-11-02 15:58:37.055	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: Stopped packet reading
2023-11-02 15:58:37.055	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: Closing from signal
2023-11-02 15:58:37.056	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: stop requested
2023-11-02 15:58:37.056	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: shutdown requested
2023-11-02 15:58:37.057	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
UUT2DEV_SER: Shutdown requested
2023-11-02 15:58:37.101	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: Stopped packet reading
2023-11-02 15:58:37.102	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: stop requested
2023-11-02 15:58:37.102	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: shutdown requested
2023-11-02 15:58:37.103	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
UUT2DEV_ETH: Shutdown requested
2023-11-02 15:58:38.059	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Shutting down microservice: DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:38.076	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Shutting down microservice complete: DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:38.105	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Shutting down microservice: DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:38.121	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Shutting down microservice complete: DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:38.153	
INFO	MicroserviceOperator	
Soft stop process successful: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:38.254	
INFO	MicroserviceOperator	
Starting: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:38.254	
INFO	MicroserviceOperator	
Soft stop process successful: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:38.259	
INFO	MicroserviceOperator	
Starting: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:39.315	
INFO		
Microservice running from: ruby plugin_microservice.rb 
2023-11-02 15:58:39.339	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Microservice initialized with config:
{"name"=>"DEFAULT__INTERFACE__UUT2DEV_SER", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_SER"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>["UUT2DEV"], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312402951028, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:39.359	
INFO		
Microservice running from: ruby plugin_microservice.rb 
2023-11-02 15:58:39.389	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Microservice initialized with config:
{"name"=>"DEFAULT__INTERFACE__UUT2DEV_ETH", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_ETH"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>[], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312399050821, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:40.006	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Ruby microservice DEFAULT__INTERFACE__UUT2DEV_SER file interface_microservice.rb passed syntax check
2023-11-02 15:58:40.081	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Ruby microservice DEFAULT__INTERFACE__UUT2DEV_ETH file interface_microservice.rb passed syntax check
2023-11-02 15:58:41.190	
INFO		
Microservice running from: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_SER
2023-11-02 15:58:41.206	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Microservice initialized with config:
{"name"=>"DEFAULT__INTERFACE__UUT2DEV_SER", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_SER"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>["UUT2DEV"], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312402951028, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:41.683	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Retrieving DEFAULT/target_archives/UUT2DEV/UUT2DEV_current.zip from targets bucket
2023-11-02 15:58:41.751	
INFO		
Microservice running from: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:41.770	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Microservice initialized with config:
{"name"=>"DEFAULT__INTERFACE__UUT2DEV_ETH", "folder_name"=>nil, "cmd"=>["ruby", "interface_microservice.rb", "DEFAULT__INTERFACE__UUT2DEV_ETH"], "work_dir"=>"/openc3/lib/openc3/microservices", "ports"=>[], "env"=>{}, "topics"=>[], "target_names"=>[], "options"=>[], "parent"=>nil, "container"=>nil, "updated_at"=>1698962312399050821, "plugin"=>"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452", "needs_dependencies"=>false, "secrets"=>[], "prefix"=>nil}
2023-11-02 15:58:41.940	
INFO	DEFAULT__INTERFACE__UUT2DEV_SER	
Processing target definition in file '/tmp/d20231102-6481-3fvr5y/targets/UUT2DEV/target.txt'
2023-11-02 15:58:42.789	
ERROR	DEFAULT__INTERFACE__UUT2DEV_ETH	
Unable to require uut_crc_protocol.rb due to cannot load such file -- uut_crc_protocol.rb. Ensure uut_crc_protocol.rb is in the OpenC3 lib directory.
2023-11-02 15:58:42.791	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Shutting down microservice: DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:42.791	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
DEFAULT__INTERFACE__UUT2DEV_ETH: stop requested
2023-11-02 15:58:42.791	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
DEFAULT__INTERFACE__UUT2DEV_ETH: shutdown requested
2023-11-02 15:58:42.803	
INFO	DEFAULT__INTERFACE__UUT2DEV_ETH	
Shutting down microservice complete: DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:43.267	
INFO	MicroserviceOperator	
Starting: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
2023-11-02 15:58:43.267	
ERROR	MicroserviceOperator	
Unexpected process died... respawning! ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH
Stdout:
{"time":1698962319359777106,"@timestamp":"2023-11-02T21:58:39.359+00:00","severity":"INFO","container_name":"c22e5aeafc36","log":"Microservice running from: ruby plugin_microservice.rb ","type":"log"}
{"time":1698962319389379556,"@timestamp":"2023-11-02T21:58:39.389+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Microservice initialized with config:
{\"name\"=>\"DEFAULT__INTERFACE__UUT2DEV_ETH\", \"folder_name\"=>nil, \"cmd\"=>[\"ruby\", \"interface_microservice.rb\", \"DEFAULT__INTERFACE__UUT2DEV_ETH\"], \"work_dir\"=>\"/openc3/lib/openc3/microservices\", \"ports\"=>[], \"env\"=>{}, \"topics\"=>[], \"target_names\"=>[], \"options\"=>[], \"parent\"=>nil, \"container\"=>nil, \"updated_at\"=>1698962312399050821, \"plugin\"=>\"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452\", \"needs_dependencies\"=>false, \"secrets\"=>[], \"prefix\"=>nil}","type":"log"}
{"time":1698962320081268438,"@timestamp":"2023-11-02T21:58:40.081+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Ruby microservice DEFAULT__INTERFACE__UUT2DEV_ETH file interface_microservice.rb passed syntax check
","type":"log"}
{"time":1698962321751577443,"@timestamp":"2023-11-02T21:58:41.751+00:00","severity":"INFO","container_name":"c22e5aeafc36","log":"Microservice running from: ruby interface_microservice.rb DEFAULT__INTERFACE__UUT2DEV_ETH","type":"log"}
{"time":1698962321770505705,"@timestamp":"2023-11-02T21:58:41.770+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Microservice initialized with config:
{\"name\"=>\"DEFAULT__INTERFACE__UUT2DEV_ETH\", \"folder_name\"=>nil, \"cmd\"=>[\"ruby\", \"interface_microservice.rb\", \"DEFAULT__INTERFACE__UUT2DEV_ETH\"], \"work_dir\"=>\"/openc3/lib/openc3/microservices\", \"ports\"=>[], \"env\"=>{}, \"topics\"=>[], \"target_names\"=>[], \"options\"=>[], \"parent\"=>nil, \"container\"=>nil, \"updated_at\"=>1698962312399050821, \"plugin\"=>\"openc3-cosmos-uut-0.2.0M.20231102145351.gem__20231102205452\", \"needs_dependencies\"=>false, \"secrets\"=>[], \"prefix\"=>nil}","type":"log"}
{"time":1698962322789921458,"@timestamp":"2023-11-02T21:58:42.789+00:00","severity":"ERROR","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Unable to require uut_crc_protocol.rb due to cannot load such file -- uut_crc_protocol.rb. Ensure uut_crc_protocol.rb is in the OpenC3 lib directory.","type":"log"}
{"time":1698962322791615806,"@timestamp":"2023-11-02T21:58:42.791+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"DEFAULT__INTERFACE__UUT2DEV_ETH: shutdown requested","type":"log"}
{"time":1698962322791838746,"@timestamp":"2023-11-02T21:58:42.791+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"DEFAULT__INTERFACE__UUT2DEV_ETH: stop requested","type":"log"}
{"time":1698962322791992948,"@timestamp":"2023-11-02T21:58:42.791+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Shutting down microservice: DEFAULT__INTERFACE__UUT2DEV_ETH","type":"log"}
{"time":1698962322803003858,"@timestamp":"2023-11-02T21:58:42.803+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__UUT2DEV_ETH","container_name":"c22e5aeafc36","log":"Shutting down microservice complete: DEFAULT__INTERFACE__UUT2DEV_ETH","type":"log"}

Stderr:
<internal:/usr/local/lib/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Unable to require uut_crc_protocol.rb due to cannot load such file -- uut_crc_protocol.rb. Ensure uut_crc_protocol.rb is in the OpenC3 lib directory. (LoadError)
	from <internal:/usr/local/lib/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:557:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:442:in `require_file'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:430:in `require_class'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:185:in `block in build'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:184:in `each'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:184:in `build'
	from interface_microservice.rb:361:in `initialize'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/microservices/microservice.rb:51:in `new'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/microservices/microservice.rb:51:in `run'
	from interface_microservice.rb:691:in `<main>'
<internal:/usr/local/lib/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- uut_crc_protocol.rb (LoadError)
	from <internal:/usr/local/lib/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:557:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:442:in `require_file'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/top_level.rb:430:in `require_class'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:185:in `block in build'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:184:in `each'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/models/interface_model.rb:184:in `build'
	from interface_microservice.rb:361:in `initialize'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/microservices/microservice.rb:51:in `new'
	from /usr/lib/ruby/gems/3.2.0/gems/openc3-5.11.3/lib/openc3/microservices/microservice.rb:51:in `run'
	from interface_microservice.rb:691:in `<main>'
```

**Environment (please complete the following information):**

- OS: RHEL 9 
- OpenC3 COSMOS Version 5.11.3
- Browser: Edge
- Container: Podman

**Comment by ryanmelt** [comment]
If you completely unmap a target from an interface, then it will remove the targets files and this will happen.

Options:
1. Move the protocol to a top level lib folder in the plugin - It will then be available to all interfaces
2. Or leave the target mapped just as a telemetry target, and disconnect the interface.  In general the key is moving the commanding, not telemetry.

**Comment by tsjordan-eng** [comment]
Both your options work. Thanks!
